In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data_set = pd.read_csv('capitalbikeshare.csv')

print(data_set.info())

X = data_set.iloc[:, [0, 3, 5]].values
y = data_set.iloc[:, -1].values
print(X[:5])
print(y[:5])

from sklearn.preprocessing import LabelEncoder
labelencoder_y =LabelEncoder()
y = labelencoder_y.fit_transform(y)
print("Sample y:",y[:5])
print("0 :",labelencoder_y.classes_[0])
print("1 :",labelencoder_y.classes_[1])

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy', min_samples_leaf=4, random_state=0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374115 entries, 0 to 374114
Data columns (total 9 columns):
 #   Column                Non-Null Count   Dtype 
---  ------                --------------   ----- 
 0   Duration              374115 non-null  int64 
 1   Start date            374115 non-null  object
 2   End date              374115 non-null  object
 3   Start station number  374115 non-null  int64 
 4   Start station         374115 non-null  object
 5   End station number    374115 non-null  int64 
 6   End station           374115 non-null  object
 7   Bike number           374115 non-null  object
 8   Member type           374115 non-null  object
dtypes: int64(3), object(6)
memory usage: 25.7+ MB
None
[[  679 31302 31307]
 [  578 31232 31609]
 [  580 31232 31609]
 [  606 31104 31509]
 [  582 31129 31118]]
['Member' 'Casual' 'Casual' 'Member' 'Member']
Sample y: [1 0 0 1 1]
0 : Casual
1 : Member
[[16396  8901]
 [10599 57633]]
